### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 28: ordinal not in range(128)

### ISSUE THREAD

**Issue by roweNN** [dansanti/user_signature_key#3]
Al momento de validar el certificado lanza el siguiente error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/user_signature_key/models/user_signature_key.py", line 242, in action_process
    self.load_cert_pk12(filecontent)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/user_signature_key/models/user_signature_key.py", line 113, in load_cert_pk12
    print('subject.CN           ', subject.CN.encode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 28: ordinal not in range(128)`

Creo que se debe a que en el certificado mi apellido contiene una ñ.

SO: Ubuntu 16.04 x64
Odoo: 8

**Comment by dansanti** [comment]
Hola! No le doy soporte a la versión 8, solamente desde la 9 en adelante.

de todas formas, comenta en el archivo py la liea 113 (y todos esos prints) y lego reinicia odoo


Saludos Cordiales

**Comment by roweNN** [comment]
El mismo problema en odoo 9

Saludos.
